server:
  port: 0

# 应用名称
spring:
  application:
    name: cloud-goods-service

  # 配置服务注册中心 nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://api.w2gd.top:8848
      username: nacos
      password: nacos