server:
  port: 8153
spring:
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://api.w2gd.top:8848
      password: nacos
      username: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_distribution_order_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000